import { Inter } from 'next/font/google';
import './globals.css';
import Header from './components/Header';
import Nav from './components/Nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="min-w-full grid grid-cols-12 grid-rows-[5vh_auto] min-h-screen p-4 text-black bg-white gap-y-5">
          <Header />
          <Nav />
          {children}
        </div>
      </body>
    </html>
  );
}
